# Network
network_layers: [16, 16, 16]
activiation_fn: "selu"
dropout_rate: 0.25
l2_reg: 0.001
batch_size: 32

optimizer:
  class_name: SGD
  config:
    learning_rate: 0.005
    momentum: 0.95
    decay: 0.001

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None