# Network
network_layers: [16, 16]
activiation_fn: "relu"
dropout_rate: 0.25
l2_reg: 0.001
batch_size: 128

optimizer:
  class_name: Adam
  config:
    learning_rate: 0.05
    decay: 0.00001

loss_fn:
  class_name: CoxPHLoss
  config:
    reduction: 'auto'
    name: None